/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Outlook (AppleScript)
 #	author : miyako
 #	2018/05/02
 #
 # --------------------------------------------------------------------------------*/

#include "libjson.h"

// --- Mail
void Outlook_Get_selection(sLONG_PTR *pResult, PackagePtr pParams);
